package org.acme.optaplanner.persistence;

public enum Role {
    OEFENLEIDER,
    ASSISTENT_OEFENLEIDER,
    ENSCENEERDER,
    WAARNEMER_MANSCHAPPEN_12,
    WAARNEMER_MANSCHAPPEN_34,
    WAARNEMER_POMPBEDIENDEN,
    WAARNEMER_BEVELVOERDER,
    BEVELVOERDER,
    POMPBEDIENDEN,
    MANSCHAP_1,
    MANSCHAP_2,
    MANSCHAP_3,
    MANSCHAP_4,
    STAGIAIRE,
    OEFENING_2;

}
